### PR TITLE
(maint) cleanup dockerfiles

### PR DESCRIPTION
**Pull request by h0tw1r3**
* [volumes](https://docs.docker.com/storage/volumes/) are for persistent data paths. /tmp, /run, /sys/cgroups, etc should never be persistent. 
* expose is to indicate to the user what ports are expected to be mapped. ports are forwarded based on the provisioner (unnecessary for docker_exp) so there's no need to explicitly expose 22.

### CODE REVIEW

**Comment by h0tw1r3** [comment]
@puppetlabs/devx any comments? There are be no backwards compatible issues that I am aware of.

**Comment by LukasAud** [comment]
Hi @h0tw1r3, we want to manually test this one before implementing it so it might take a bit more time. If you have already performed any tests on your side, please let us know the results.

**Comment by david22swan** [comment]
Closing and re-opening to trigger new test workflow

**Comment by h0tw1r3** [comment]
Failures are caused by stdlib fixtures pinning the puppet_agent module :( and ubuntu 24.04 nightly isn't available yet.

Submitting a PR to stdlib to remove the fixtures pin.

**Pull request merged**
